// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("Address")]
public partial class Address
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingId { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string ApartmentId { get; set; }

    [Required]
    public bool? IsApartment { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Country { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string City { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("ApartmentId")]
    [InverseProperty("Addresses")]
    public virtual Apartment Apartment { get; set; }

    [ForeignKey("BuildingId")]
    [InverseProperty("Addresses")]
    public virtual Building Building { get; set; }
}