// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("Apartment")]
[Index("Code", Name = "Apartment_Code", IsUnique = true)]
public partial class Apartment
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string FloorId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(24)]
    [Unicode(false)]
    public string Door { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Apartment")]
    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    [ForeignKey("FloorId")]
    [InverseProperty("Apartments")]
    public virtual Floor Floor { get; set; }
}