// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("BuildingImage")]
[Index("FilePath", Name = "UQ__Building__48D910BD6BD715C4", IsUnique = true)]
[Index("FileName", Name = "UQ__Building__589E6EECCA2478BC", IsUnique = true)]
public partial class BuildingImage
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingImageId { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string FileName { get; set; }

    [Required]
    [StringLength(1024)]
    [Unicode(false)]
    public string FilePath { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string AltText { get; set; }

    public bool IsCoverImage { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("BuildingId")]
    [InverseProperty("BuildingImages")]
    public virtual Building Building { get; set; }
}