// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("BuildingCompany")]
[Index("Cif", Name = "BuildingCompany_Cif", IsUnique = true)]
[Index("Name", Name = "UQ__Building__737584F65B435540", IsUnique = true)]
public partial class BuildingCompany
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(9)]
    [Unicode(false)]
    public string Cif { get; set; }

    [StringLength(1024)]
    [Unicode(false)]
    public string Website { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("BuildingCompany")]
    public virtual ICollection<Building> Buildings { get; set; } = new List<Building>();

    [InverseProperty("BuildingCompany")]
    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}