// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[PrimaryKey("BuildingId", "StatusId", "CreatedAt")]
[Table("BuildingStatusLog")]
public partial class BuildingStatusLog
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingId { get; set; }

    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string StatusId { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("BuildingId")]
    [InverseProperty("BuildingStatusLogs")]
    public virtual Building Building { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("BuildingStatusLogs")]
    public virtual Status Status { get; set; }
}