// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("District")]
[Index("Zipcode", Name = "District_Zipcode", IsUnique = true)]
[Index("Name", Name = "UQ__District__737584F64B48E22F", IsUnique = true)]
public partial class District
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Zipcode { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Country { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string City { get; set; }

    public int BuildingCount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("District")]
    public virtual ICollection<Building> Buildings { get; set; } = new List<Building>();

    [ForeignKey("DistrictId")]
    [InverseProperty("Districts")]
    public virtual ICollection<Street> Streets { get; set; } = new List<Street>();
}