// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("Floor")]
public partial class Floor
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingId { get; set; }

    public int FloorNumber { get; set; }

    [Required]
    public bool? HasLift { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Floor")]
    public virtual ICollection<Apartment> Apartments { get; set; } = new List<Apartment>();

    [ForeignKey("BuildingId")]
    [InverseProperty("Floors")]
    public virtual Building Building { get; set; }
}