// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("Purchase")]
public partial class Purchase
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingId { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingCompanyId { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string RequestId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("BuildingId")]
    [InverseProperty("Purchases")]
    public virtual Building Building { get; set; }

    [ForeignKey("BuildingCompanyId")]
    [InverseProperty("Purchases")]
    public virtual BuildingCompany BuildingCompany { get; set; }

    [ForeignKey("RequestId")]
    [InverseProperty("Purchases")]
    public virtual Request Request { get; set; }
}