// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[PrimaryKey("RequestId", "StatusId", "CreatedAt")]
[Table("RequestStatusLog")]
public partial class RequestStatusLog
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string RequestId { get; set; }

    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string StatusId { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("RequestId")]
    [InverseProperty("RequestStatusLogs")]
    public virtual Request Request { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("RequestStatusLogs")]
    public virtual Status Status { get; set; }
}