// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("Request")]
public partial class Request
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string BuildingId { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal Price { get; set; }

    public float MaintenancePrice { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Required]
    [StringLength(36)]
    [Unicode(false)]
    public string StatusId { get; set; }

    [ForeignKey("BuildingId")]
    [InverseProperty("Requests")]
    public virtual Building Building { get; set; }

    [InverseProperty("Request")]
    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();

    [InverseProperty("Request")]
    public virtual ICollection<RequestStatusLog> RequestStatusLogs { get; set; } = new List<RequestStatusLog>();

    [ForeignKey("StatusId")]
    [InverseProperty("Requests")]
    public virtual Status Status { get; set; }
}