// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("Status")]
[Index("Name", Name = "UQ__Status__737584F6D5F12725", IsUnique = true)]
public partial class Status
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(48)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<BuildingStatusLog> BuildingStatusLogs { get; set; } = new List<BuildingStatusLog>();

    [InverseProperty("Status")]
    public virtual ICollection<Building> Buildings { get; set; } = new List<Building>();

    [InverseProperty("Status")]
    public virtual ICollection<RequestStatusLog> RequestStatusLogs { get; set; } = new List<RequestStatusLog>();

    [InverseProperty("Status")]
    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();
}