// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyData.Dominio;

[Table("Street")]
[Index("Code", Name = "Street_Code", IsUnique = true)]
public partial class Street
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string Id { get; set; }

    [Required]
    [StringLength(24)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Street")]
    public virtual ICollection<Building> Buildings { get; set; } = new List<Building>();

    [ForeignKey("StreetId")]
    [InverseProperty("Streets")]
    public virtual ICollection<District> Districts { get; set; } = new List<District>();
}